<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
    <Version>1.1.0</Version>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-UScheduler-040d8105-9e07-4024-a632-cbe091387b66</UserSecretsId>
    <OutputType>exe</OutputType>
    <PublishSingleFile Condition="'$(Configuration)' == 'Release'">false</PublishSingleFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MaksIT.UScheduler.Shared\MaksIT.UScheduler.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MaksIT.Core" Version="1.6.8" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Systemd" Version="10.0.9" />
    <PackageReference Include="Microsoft.PowerShell.Commands.Diagnostics" Version="7.6.3" />
    <PackageReference Include="Microsoft.PowerShell.Commands.Management" Version="7.6.3" />
    <PackageReference Include="Microsoft.PowerShell.Commands.Utility" Version="7.6.3" />
    <PackageReference Include="Microsoft.PowerShell.ConsoleHost" Version="7.6.3" />
    <PackageReference Include="Microsoft.WSMan.Management" Version="7.6.3" />
    <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="10.0.9" />
    <PackageReference Include="System.Management.Automation" Version="7.6.3" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\PublishProfiles\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\README.md;..\..\LICENSE.md;..\..\CHANGELOG.md">
      <Link>%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\..\assets\**\*" Link="assets\%(RecursiveDir)%(Filename)%(Extension)">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
