<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MaksIT.UScheduler.Shared\MaksIT.UScheduler.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MaksIT.Core" Version="1.6.8" />
    <PackageReference Include="MaksIT.Results" Version="2.0.3" />
    <PackageReference Include="System.Management.Automation" Version="7.6.3" />
  </ItemGroup>

</Project>
